var searchData=
[
  ['safety_0',['Safety',['../api.html#api_exception_safety',1,'Exception Safety'],['../usage_guide.html#ug_exception_safety',1,'Exception Safety'],['../api.html#api_thread_safety',1,'Thread Safety'],['../index.html#autotoc_md26',1,'Thread Safety']]],
  ['scoped_5fresource_1',['scoped_resource',['../classsiddiqsoft_1_1arrp_1_1scoped__resource.html',1,'siddiqsoft::arrp::scoped_resource&lt; T &gt;'],['../classsiddiqsoft_1_1arrp_1_1scoped__resource.html#a00c6980fe93ed276f6700d6e1853d3eb',1,'siddiqsoft::arrp::scoped_resource::scoped_resource()=delete'],['../classsiddiqsoft_1_1arrp_1_1scoped__resource.html#a65fa62b079694a829ced128cf0bb99da',1,'siddiqsoft::arrp::scoped_resource::scoped_resource(PutbackCallbackFunc &amp;&amp;f, T &amp;&amp;src)'],['../classsiddiqsoft_1_1arrp_1_1scoped__resource.html#aa0b274f25119c124682b8efd5f40a75d',1,'siddiqsoft::arrp::scoped_resource::scoped_resource(const T &amp;)=delete'],['../classsiddiqsoft_1_1arrp_1_1scoped__resource.html#a45b3ab8778376f5b6c21dfcc652cd0e4',1,'siddiqsoft::arrp::scoped_resource::scoped_resource(scoped_resource &amp;&amp;src) noexcept'],['../classsiddiqsoft_1_1arrp_1_1scoped__resource.html#a471e843872dcd72af9cae100ab2b756b',1,'siddiqsoft::arrp::scoped_resource::scoped_resource(PutbackCallbackFunc &amp;&amp;f, Args &amp;&amp;... args)']]],
  ['scoped_5fresource_20class_2',['scoped_resource Class',['../api.html#api_scoped_resource',1,'']]],
  ['see_20also_3',['See Also',['../index.html#see_also',1,'']]],
  ['seed_5fto_5fpool_4',['seed_to_pool',['../classsiddiqsoft_1_1arrp_1_1resource__pool.html#aaeb8a2b1050aa45ec0f6fddcb4bdc733',1,'siddiqsoft::arrp::resource_pool::seed_to_pool(Args &amp;&amp;... args) -&gt; std::expected&lt; void, pool_error &gt;'],['../classsiddiqsoft_1_1arrp_1_1resource__pool.html#a2cf41b9a148a7f39db22c3fcc25eb96b',1,'siddiqsoft::arrp::resource_pool::seed_to_pool(T &amp;&amp;item) -&gt; std::expected&lt; void, pool_error &gt;'],['../api.html#autotoc_md4',1,'seed_to_pool()']]],
  ['shared_5fptr_5',['Using shared_ptr',['../usage_guide.html#ug_shared_ptr',1,'']]],
  ['size_6',['size',['../classsiddiqsoft_1_1arrp_1_1resource__pool.html#ad02d55907e39464721adf565cefd5db2',1,'siddiqsoft::arrp::resource_pool::size()'],['../api.html#autotoc_md5',1,'size()']]],
  ['state_7',['Monitoring Pool State',['../usage_guide.html#ug_monitoring',1,'']]]
];
