var searchData=
[
  ['m_5fis_5fvalid_0',['m_is_valid',['../classsiddiqsoft_1_1arrp_1_1scoped__resource.html#a231bcb2ca5e2816bc814684889081383',1,'siddiqsoft::arrp::scoped_resource']]],
  ['m_5fputback_5fcallback_1',['m_putback_callback',['../classsiddiqsoft_1_1arrp_1_1scoped__resource.html#a3ca34586882c8ad3a9520ccf281f213a',1,'siddiqsoft::arrp::scoped_resource']]],
  ['m_5frsrc_2',['m_rsrc',['../classsiddiqsoft_1_1arrp_1_1scoped__resource.html#a7a206dc66fef807bc0720c7b942be24c',1,'siddiqsoft::arrp::scoped_resource']]],
  ['main_20components_3',['Main Components',['../index.html#components',1,'']]],
  ['management_4',['Management',['../usage_guide.html#rp_capacity',1,'Capacity Management'],['../usage_guide.html#bp_lifetime',1,'Lifetime Management'],['../security.html#autotoc_md87',1,'Resource Management']]],
  ['manual_20integration_5',['Manual Integration',['../index.html#autotoc_md68',1,'']]],
  ['members_6',['Static Members',['../api.html#autotoc_md15',1,'']]],
  ['memory_20safety_7',['Memory Safety',['../security.html#autotoc_md83',1,'']]],
  ['method_8',['get Method',['../api.html#autotoc_md30',1,'']]],
  ['methods_9',['Methods',['../api.html#autotoc_md28',1,'Access Methods'],['../quick_reference.html#qr_methods',1,'Common Methods'],['../security.html#autotoc_md94',1,'Critical Rule: Factory Callbacks Must Not Call Pool Methods'],['../api.html#autotoc_md32',1,'Lifecycle Methods'],['../api.html#autotoc_md9',1,'Methods'],['../usage_guide.html#rp_methods',1,'Resource Pool Methods']]],
  ['modern_20c_10',['ARRP - Auto Returning Resource Pool for Modern C++',['../index.html',1,'']]],
  ['monitoring_11',['Monitoring',['../quick_reference.html#autotoc_md82',1,'Example 5: Monitoring'],['../usage_guide.html#bp_monitoring',1,'Monitoring'],['../examples.html#ex_monitoring',1,'Pool Monitoring']]],
  ['monitoring_20and_20diagnostics_12',['Monitoring and Diagnostics',['../security.html#monitoring',1,'']]],
  ['monitoring_20best_20practices_13',['Monitoring Best Practices',['../security.html#autotoc_md106',1,'']]],
  ['monitoring_20pool_20state_14',['Monitoring Pool State',['../api.html#autotoc_md44',1,'']]],
  ['move_20assignment_20operator_15',['Move Assignment Operator',['../api.html#autotoc_md27',1,'']]],
  ['move_20constructor_16',['Move Constructor',['../api.html#autotoc_md26',1,'']]],
  ['multi_20threaded_17',['Example 3: Multi-threaded',['../quick_reference.html#autotoc_md80',1,'']]],
  ['multi_20threaded_20usage_18',['Multi threaded Usage',['../quick_reference.html#qr_pattern_multithreaded',1,'Multi-threaded Usage'],['../usage_guide.html#rp_multithreaded',1,'Multi-threaded Usage'],['../getting_started.html#autotoc_md62',1,'Pattern 3: Multi-threaded Usage']]],
  ['multi_20threaded_20usage_20example_19',['Multi-threaded Usage Example',['../index.html#resource_pool_multithreaded',1,'']]],
  ['must_20not_20call_20pool_20methods_20',['Critical Rule: Factory Callbacks Must Not Call Pool Methods',['../security.html#autotoc_md94',1,'']]],
  ['mutex_20configuration_21',['Mutex Configuration',['../api.html#autotoc_md54',1,'']]],
  ['mutex_20strategy_22',['Understanding the Mutex Strategy',['../security.html#autotoc_md93',1,'']]]
];
