var searchData=
[
  ['c_0',['ARRP - Auto Returning Resource Pool for Modern C++',['../index.html',1,'']]],
  ['call_20pool_20methods_1',['Critical Rule: Factory Callbacks Must Not Call Pool Methods',['../security.html#autotoc_md80',1,'']]],
  ['callback_20practices_2',['Callback Practices',['../security.html#autotoc_md74',1,'✅ Good Callback Practices'],['../security.html#autotoc_md75',1,'❌ Bad Callback Practices']]],
  ['callback_20security_3',['Callback Security',['../security.html#callback_security',1,'']]],
  ['callbackdonotautoaddresource_4',['CallbackDoNotAutoAddResource',['../classsiddiqsoft_1_1arrp_1_1resource__pool.html#ad1c762915e349bd3cd3562bf305a61b4',1,'siddiqsoft::arrp::resource_pool']]],
  ['callbacks_20must_20not_20call_20pool_20methods_5',['Critical Rule: Factory Callbacks Must Not Call Pool Methods',['../security.html#autotoc_md80',1,'']]],
  ['capacity_20limits_6',['Capacity Limits',['../security.html#autotoc_md83',1,'']]],
  ['capacity_20management_7',['Capacity Management',['../usage_guide.html#rp_capacity',1,'']]],
  ['capacity_20planning_8',['Capacity Planning',['../usage_guide.html#bp_capacity',1,'']]],
  ['checklist_9',['Security Checklist',['../security.html#security_checklist',1,'']]],
  ['circular_20dependencies_10',['Circular Dependencies',['../security.html#autotoc_md76',1,'']]],
  ['clang_2010_11',['Clang 10+',['../getting_started.html#autotoc_md45',1,'']]],
  ['cleanup_12',['Resource Cleanup',['../security.html#autotoc_md90',1,'']]],
  ['clear_13',['clear',['../api.html#autotoc_md11',1,'clear'],['../quick_reference.html#autotoc_md60',1,'clear()'],['../usage_guide.html#autotoc_md96',1,'clear()']]],
  ['client_20connection_20pool_14',['HTTP Client Connection Pool',['../examples.html#ex_http_client',1,'']]],
  ['cmake_20recommended_15',['CMake Recommended',['../getting_started.html#autotoc_md41',1,'Using CMake (Recommended)'],['../index.html#autotoc_md52',1,'Using CMake (Recommended)']]],
  ['common_20issues_16',['Common Issues',['../quick_reference.html#qr_troubleshooting',1,'']]],
  ['common_20methods_17',['Common Methods',['../quick_reference.html#qr_methods',1,'']]],
  ['common_20patterns_18',['Common Patterns',['../api.html#autotoc_md31',1,'Common Patterns'],['../getting_started.html#common_patterns',1,'Common Patterns']]],
  ['compilation_19',['Compilation',['../quick_reference.html#qr_compilation',1,'']]],
  ['compilation_20errors_20',['Compilation Errors',['../getting_started.html#autotoc_md50',1,'']]],
  ['compiler_20setup_21',['Compiler Setup',['../getting_started.html#compiler_setup',1,'']]],
  ['components_22',['Main Components',['../index.html#components',1,'']]],
  ['components_20at_20a_20glance_23',['Components at a Glance',['../quick_reference.html#qr_components',1,'']]],
  ['concept_24',['NonNumericMoveConstructible Concept',['../quick_reference.html#autotoc_md63',1,'']]],
  ['concepts_25',['Concepts',['../api.html#autotoc_md28',1,'']]],
  ['connection_20pool_26',['Connection Pool',['../examples.html#ex_database_connections',1,'Database Connection Pool'],['../examples.html#ex_http_client',1,'HTTP Client Connection Pool']]],
  ['considerations_27',['Considerations',['../api.html#autotoc_md38',1,'Performance Considerations'],['../usage_guide.html#performance',1,'Performance Considerations']]],
  ['consistency_28',['Lock Ordering and Consistency',['../security.html#autotoc_md81',1,'']]],
  ['constraints_29',['Type Constraints',['../quick_reference.html#qr_constraints',1,'']]],
  ['constructor_30',['Constructor',['../api.html#autotoc_md6',1,'Constructor'],['../api.html#autotoc_md19',1,'Constructor'],['../api.html#autotoc_md20',1,'Move Constructor']]],
  ['contents_31',['Table of Contents',['../api.html#autotoc_md0',1,'']]],
  ['conversion_20operator_32',['Type Conversion Operator',['../api.html#autotoc_md24',1,'']]],
  ['copyright_33',['Copyright',['../index.html#copyright',1,'']]],
  ['critical_20exceptions_34',['Critical Exceptions',['../security.html#autotoc_md86',1,'']]],
  ['critical_20rule_3a_20factory_20callbacks_20must_20not_20call_20pool_20methods_35',['Critical Rule: Factory Callbacks Must Not Call Pool Methods',['../security.html#autotoc_md80',1,'']]],
  ['custom_20factory_36',['Custom Factory',['../quick_reference.html#qr_pattern_factory',1,'Custom Factory'],['../quick_reference.html#autotoc_md65',1,'Example 2: Custom Factory'],['../api.html#autotoc_md33',1,'Resource Pool with Custom Factory']]],
  ['custom_20factory_20example_37',['Custom Factory Example',['../index.html#resource_pool_custom',1,'']]],
  ['custom_20resource_20factory_38',['Custom Resource Factory',['../examples.html#ex_custom_factory',1,'Custom Resource Factory'],['../usage_guide.html#rp_factory',1,'Custom Resource Factory'],['../getting_started.html#autotoc_md47',1,'Pattern 2: Custom Resource Factory']]],
  ['custom_20resource_20types_39',['Custom Resource Types',['../usage_guide.html#adv_custom_types',1,'']]]
];
