var searchData=
[
  ['c_0',['ARRP - Auto Returning Resource Pool for Modern C++',['../index.html',1,'']]],
  ['call_20pool_20methods_1',['Critical Rule: Factory Callbacks Must Not Call Pool Methods',['../security.html#autotoc_md103',1,'']]],
  ['callback_20practices_2',['Callback Practices',['../security.html#autotoc_md97',1,'✅ Good Callback Practices'],['../security.html#autotoc_md98',1,'❌ Bad Callback Practices']]],
  ['callback_20security_3',['Callback Security',['../security.html#callback_security',1,'']]],
  ['callbackdonotautoaddresource_4',['CallbackDoNotAutoAddResource',['../classsiddiqsoft_1_1arrp_1_1resource__pool.html#ad1c762915e349bd3cd3562bf305a61b4',1,'siddiqsoft::arrp::resource_pool::CallbackDoNotAutoAddResource'],['../api.html#autotoc_md24',1,'CallbackDoNotAutoAddResource']]],
  ['callbacks_20must_20not_20call_20pool_20methods_5',['Critical Rule: Factory Callbacks Must Not Call Pool Methods',['../security.html#autotoc_md103',1,'']]],
  ['capacity_6',['InitCapacity - Initial Pool Capacity',['../api.html#autotoc_md8',1,'']]],
  ['capacity_20constraint_7',['1. Capacity Constraint',['../api.html#autotoc_md10',1,'']]],
  ['capacity_20limits_8',['Capacity Limits',['../security.html#autotoc_md106',1,'']]],
  ['capacity_20management_9',['Capacity Management',['../usage_guide.html#rp_capacity',1,'']]],
  ['capacity_20planning_10',['Capacity Planning',['../usage_guide.html#bp_capacity',1,'']]],
  ['checklist_11',['Security Checklist',['../security.html#security_checklist',1,'']]],
  ['circular_20dependencies_12',['Circular Dependencies',['../security.html#autotoc_md99',1,'']]],
  ['clang_2010_13',['Clang 10+',['../getting_started.html#autotoc_md68',1,'']]],
  ['clause_14',['Template Constraints (Requires Clause)',['../api.html#autotoc_md9',1,'']]],
  ['cleanup_15',['Resource Cleanup',['../security.html#autotoc_md113',1,'']]],
  ['clear_16',['clear',['../api.html#autotoc_md21',1,'clear'],['../quick_reference.html#autotoc_md83',1,'clear()'],['../usage_guide.html#autotoc_md119',1,'clear()']]],
  ['client_20connection_20pool_17',['HTTP Client Connection Pool',['../examples.html#ex_http_client',1,'']]],
  ['cmake_20recommended_18',['CMake Recommended',['../getting_started.html#autotoc_md64',1,'Using CMake (Recommended)'],['../index.html#autotoc_md75',1,'Using CMake (Recommended)']]],
  ['common_20issues_19',['Common Issues',['../quick_reference.html#qr_troubleshooting',1,'']]],
  ['common_20methods_20',['Common Methods',['../quick_reference.html#qr_methods',1,'']]],
  ['common_20patterns_21',['Common Patterns',['../api.html#autotoc_md48',1,'Common Patterns'],['../getting_started.html#common_patterns',1,'Common Patterns']]],
  ['compilation_22',['Compilation',['../quick_reference.html#qr_compilation',1,'']]],
  ['compilation_20errors_23',['Compilation Errors',['../getting_started.html#autotoc_md73',1,'']]],
  ['compiler_20setup_24',['Compiler Setup',['../getting_started.html#compiler_setup',1,'']]],
  ['compiler_20support_25',['Compiler Support',['../api.html#autotoc_md61',1,'']]],
  ['components_26',['Main Components',['../index.html#components',1,'']]],
  ['components_20at_20a_20glance_27',['Components at a Glance',['../quick_reference.html#qr_components',1,'']]],
  ['concept_28',['NonNumericMoveConstructible Concept',['../quick_reference.html#autotoc_md86',1,'']]],
  ['concepts_29',['Concepts',['../api.html#autotoc_md45',1,'']]],
  ['configuration_30',['Mutex Configuration',['../api.html#autotoc_md63',1,'']]],
  ['connection_20pool_31',['Connection Pool',['../examples.html#ex_database_connections',1,'Database Connection Pool'],['../examples.html#ex_http_client',1,'HTTP Client Connection Pool']]],
  ['considerations_32',['Considerations',['../api.html#autotoc_md57',1,'Performance Considerations'],['../usage_guide.html#performance',1,'Performance Considerations']]],
  ['consistency_33',['Lock Ordering and Consistency',['../security.html#autotoc_md104',1,'']]],
  ['constraint_34',['Constraint',['../api.html#autotoc_md10',1,'1. Capacity Constraint'],['../api.html#autotoc_md11',1,'2. Resource Type Constraint'],['../api.html#autotoc_md12',1,'3. Wrapper Type Constraint']]],
  ['constraints_35',['Type Constraints',['../quick_reference.html#qr_constraints',1,'']]],
  ['constraints_20and_20limitations_36',['Constraints and Limitations',['../api.html#autotoc_md25',1,'']]],
  ['constraints_20requires_20clause_37',['Template Constraints (Requires Clause)',['../api.html#autotoc_md9',1,'']]],
  ['constructor_38',['Constructor',['../api.html#autotoc_md35',1,'Explicit Constructor'],['../api.html#autotoc_md36',1,'Move Constructor']]],
  ['constructor_20with_20auto_20add_20policy_39',['Constructor with Auto-Add Policy',['../api.html#autotoc_md16',1,'']]],
  ['constructor_20with_20custom_20factory_40',['Constructor with Custom Factory',['../api.html#autotoc_md15',1,'']]],
  ['constructors_41',['Constructors',['../api.html#autotoc_md14',1,'Constructors'],['../api.html#autotoc_md34',1,'Constructors']]],
  ['contents_42',['Table of Contents',['../api.html#autotoc_md0',1,'']]],
  ['conversion_20operator_43',['Type Conversion Operator',['../api.html#autotoc_md40',1,'']]],
  ['copyright_44',['Copyright',['../index.html#copyright',1,'']]],
  ['critical_20exceptions_45',['Critical Exceptions',['../security.html#autotoc_md109',1,'']]],
  ['critical_20rule_3a_20factory_20callbacks_20must_20not_20call_20pool_20methods_46',['Critical Rule: Factory Callbacks Must Not Call Pool Methods',['../security.html#autotoc_md103',1,'']]],
  ['custom_20factory_47',['Custom Factory',['../api.html#autotoc_md15',1,'Constructor with Custom Factory'],['../quick_reference.html#qr_pattern_factory',1,'Custom Factory'],['../quick_reference.html#autotoc_md88',1,'Example 2: Custom Factory'],['../api.html#autotoc_md50',1,'Resource Pool with Custom Factory']]],
  ['custom_20factory_20example_48',['Custom Factory Example',['../index.html#resource_pool_custom',1,'']]],
  ['custom_20resource_20factory_49',['Custom Resource Factory',['../examples.html#ex_custom_factory',1,'Custom Resource Factory'],['../usage_guide.html#rp_factory',1,'Custom Resource Factory'],['../getting_started.html#autotoc_md70',1,'Pattern 2: Custom Resource Factory']]],
  ['custom_20resource_20types_50',['Custom Resource Types',['../usage_guide.html#adv_custom_types',1,'']]]
];
