var searchData=
[
  ['recommended_0',['Recommended',['../getting_started.html#autotoc_md41',1,'Using CMake (Recommended)'],['../index.html#autotoc_md52',1,'Using CMake (Recommended)']]],
  ['reference_1',['Reference',['../api.html',1,'API Reference'],['../quick_reference.html',1,'Quick Reference']]],
  ['reporting_2',['Vulnerability Reporting',['../security.html#vulnerability_reporting',1,'']]],
  ['requirements_3',['Requirements',['../index.html#requirements',1,'Requirements'],['../quick_reference.html#qr_requirements',1,'Requirements']]],
  ['resource_20access_4',['Resource Access',['../security.html#autotoc_md88',1,'']]],
  ['resource_20borrowing_5',['Pattern 1: Basic Resource Borrowing',['../getting_started.html#autotoc_md46',1,'']]],
  ['resource_20cleanup_6',['Resource Cleanup',['../security.html#autotoc_md90',1,'']]],
  ['resource_20exceptions_7',['Resource Exceptions',['../security.html#autotoc_md85',1,'']]],
  ['resource_20exhaustion_20prevention_8',['Resource Exhaustion Prevention',['../security.html#resource_exhaustion',1,'']]],
  ['resource_20factory_9',['Resource Factory',['../examples.html#ex_custom_factory',1,'Custom Resource Factory'],['../usage_guide.html#rp_factory',1,'Custom Resource Factory'],['../getting_started.html#autotoc_md47',1,'Pattern 2: Custom Resource Factory']]],
  ['resource_20invalidation_10',['Resource Invalidation',['../getting_started.html#autotoc_md49',1,'Pattern 4: Resource Invalidation'],['../api.html#autotoc_md34',1,'Resource Invalidation'],['../examples.html#ex_resource_invalidation',1,'Resource Invalidation'],['../quick_reference.html#qr_pattern_invalidate',1,'Resource Invalidation'],['../usage_guide.html#adv_resource_invalidation',1,'Resource Invalidation']]],
  ['resource_20management_11',['Resource Management',['../security.html#autotoc_md73',1,'']]],
  ['resource_20pool_12',['Resource Pool',['../usage_guide.html#resource_pool',1,'']]],
  ['resource_20pool_20example_13',['Basic Resource Pool Example',['../index.html#resource_pool_basic',1,'']]],
  ['resource_20pool_20for_20modern_20c_14',['ARRP - Auto Returning Resource Pool for Modern C++',['../index.html',1,'']]],
  ['resource_20pool_20methods_15',['Resource Pool Methods',['../usage_guide.html#rp_methods',1,'']]],
  ['resource_20pool_20usage_16',['Basic Resource Pool Usage',['../api.html#autotoc_md32',1,'']]],
  ['resource_20pool_20with_20custom_20factory_17',['Resource Pool with Custom Factory',['../api.html#autotoc_md33',1,'']]],
  ['resource_20types_18',['Resource Types',['../usage_guide.html#adv_custom_types',1,'Custom Resource Types'],['../usage_guide.html#bp_resource_types',1,'Resource Types']]],
  ['resource_20usage_19',['Scoped Resource Usage',['../examples.html#ex_scoped_usage',1,'']]],
  ['resource_20wrapper_20',['Scoped Resource Wrapper',['../usage_guide.html#rp_scoped_resource',1,'']]],
  ['resource_5fpool_21',['resource_pool',['../classsiddiqsoft_1_1arrp_1_1resource__pool.html',1,'siddiqsoft::arrp::resource_pool&lt; T, SRT, InitCapacity &gt;'],['../classsiddiqsoft_1_1arrp_1_1resource__pool.html#a1af18960c0ae03a482e0ff2c245aaff7',1,'siddiqsoft::arrp::resource_pool::resource_pool(auto_add_policy add_policy=auto_add_policy::NoGrow)'],['../classsiddiqsoft_1_1arrp_1_1resource__pool.html#a3f49a8f3ce97a69f0e8df2dcb3c52381',1,'siddiqsoft::arrp::resource_pool::resource_pool(resource_pool &amp;)=delete'],['../classsiddiqsoft_1_1arrp_1_1resource__pool.html#aa321fb35cc3b4e1b12b19253c20ac779',1,'siddiqsoft::arrp::resource_pool::resource_pool(resource_pool &amp;&amp;src)=delete'],['../api.html#autotoc_md2',1,'resource_pool'],['../api.html#autotoc_md39',1,'resource_pool'],['../usage_guide.html#autotoc_md98',1,'resource_pool'],['../quick_reference.html#autotoc_md55',1,'resource_pool&amp;lt;T, SRT, InitCapacity&amp;gt;']]],
  ['resources_22',['Additional Resources',['../security.html#security_resources',1,'']]],
  ['return_5fto_5fpool_23',['return_to_pool',['../api.html#autotoc_md10',1,'return_to_pool'],['../usage_guide.html#autotoc_md94',1,'return_to_pool()']]],
  ['return_5fto_5fpool_20t_24',['return_to_pool(T&amp;amp;&amp;amp;)',['../quick_reference.html#autotoc_md58',1,'']]],
  ['returning_20resource_20pool_20for_20modern_20c_25',['ARRP - Auto Returning Resource Pool for Modern C++',['../index.html',1,'']]],
  ['rule_3a_20factory_20callbacks_20must_20not_20call_20pool_20methods_26',['Critical Rule: Factory Callbacks Must Not Call Pool Methods',['../security.html#autotoc_md80',1,'']]],
  ['runtime_20issues_27',['Runtime Issues',['../getting_started.html#autotoc_md51',1,'']]]
];
