var searchData=
[
  ['safety_0',['Safety',['../security.html#autotoc_md85',1,'Exception Safety'],['../security.html#autotoc_md83',1,'Memory Safety'],['../security.html#shutdown_safety',1,'Shutdown Safety'],['../api.html#autotoc_md18',1,'Thread Safety'],['../api.html#autotoc_md46',1,'Thread Safety'],['../security.html#autotoc_md84',1,'Thread Safety'],['../security.html#thread_safety',1,'Thread Safety'],['../security.html#autotoc_md86',1,'Type Safety']]],
  ['scoped_20resource_20usage_1',['Scoped Resource Usage',['../examples.html#ex_scoped_usage',1,'']]],
  ['scoped_20resource_20wrapper_2',['Scoped Resource Wrapper',['../usage_guide.html#rp_scoped_resource',1,'']]],
  ['scoped_5fresource_3',['scoped_resource',['../classsiddiqsoft_1_1arrp_1_1scoped__resource.html',1,'siddiqsoft::arrp::scoped_resource&lt; T &gt;'],['../classsiddiqsoft_1_1arrp_1_1scoped__resource.html#a00c6980fe93ed276f6700d6e1853d3eb',1,'siddiqsoft::arrp::scoped_resource::scoped_resource()=delete'],['../classsiddiqsoft_1_1arrp_1_1scoped__resource.html#aa0b274f25119c124682b8efd5f40a75d',1,'siddiqsoft::arrp::scoped_resource::scoped_resource(const T &amp;)=delete'],['../api.html#autotoc_md20',1,'scoped_resource'],['../api.html#autotoc_md50',1,'scoped_resource'],['../quick_reference.html#autotoc_md70',1,'scoped_resource&amp;lt;T&amp;gt;']]],
  ['security_4',['Callback Security',['../security.html#callback_security',1,'']]],
  ['security_20checklist_5',['Security Checklist',['../security.html#security_checklist',1,'']]],
  ['security_20features_6',['Built-in Security Features',['../security.html#security_features',1,'']]],
  ['security_20guide_7',['Security Guide',['../security.html',1,'']]],
  ['see_20also_8',['See Also',['../index.html#see_also',1,'']]],
  ['serialization_9',['Serialization',['../security.html#autotoc_md105',1,'JSON Serialization'],['../usage_guide.html#adv_json_serialization',1,'JSON Serialization']]],
  ['setup_10',['Compiler Setup',['../getting_started.html#compiler_setup',1,'']]],
  ['shutdown_11',['Graceful Shutdown',['../security.html#autotoc_md103',1,'']]],
  ['shutdown_20safety_12',['Shutdown Safety',['../security.html#shutdown_safety',1,'']]],
  ['size_13',['size',['../api.html#autotoc_md10',1,'size'],['../quick_reference.html#autotoc_md73',1,'size()'],['../usage_guide.html#autotoc_md109',1,'size()']]],
  ['start_14',['Quick Start',['../index.html#quickstart',1,'']]],
  ['started_15',['Getting Started',['../getting_started.html',1,'']]],
  ['state_16',['Monitoring Pool State',['../api.html#autotoc_md44',1,'']]],
  ['static_20members_17',['Static Members',['../api.html#autotoc_md15',1,'']]],
  ['steps_18',['Next Steps',['../getting_started.html#next_steps',1,'']]],
  ['strategy_19',['Understanding the Mutex Strategy',['../security.html#autotoc_md93',1,'']]],
  ['studio_202019_20or_20later_20',['Visual Studio 2019 or later',['../getting_started.html#autotoc_md57',1,'']]],
  ['support_21',['Compiler Support',['../api.html#autotoc_md52',1,'']]]
];
