var searchData=
[
  ['reference_0',['API reference',['../api_reference.html',1,'']]],
  ['requirements_1',['Include and requirements',['../api_reference.html#api_include',1,'']]],
  ['resource_2',['resource',['../usage_guide.html#usage_invalidating',1,'Discarding a resource'],['../usage_guide.html#usage_waiting',1,'Waiting for a resource']]],
  ['resource_5fcallback_5ft_3',['resource_callback_t',['../classsiddiqsoft_1_1arrp_1_1resource__pool.html#ad79f0e10f78e7e2be164e7d08c25e883',1,'siddiqsoft::arrp::resource_pool']]],
  ['resource_5fguard_4',['resource_guard',['../classsiddiqsoft_1_1arrp_1_1resource__guard.html',1,'siddiqsoft::arrp::resource_guard&lt; T &gt;'],['../classsiddiqsoft_1_1arrp_1_1resource__guard.html#a3495caae58e003881e976318559ba06e',1,'siddiqsoft::arrp::resource_guard::resource_guard()'],['../classsiddiqsoft_1_1arrp_1_1resource__guard.html#af5949392e4dac60ef492b5585d4ac35b',1,'siddiqsoft::arrp::resource_guard::resource_guard(const resource_guard &amp;)=delete'],['../classsiddiqsoft_1_1arrp_1_1resource__guard.html#a6f177e84230f911f734db42ab5998e42',1,'siddiqsoft::arrp::resource_guard::resource_guard(const pool_error &amp;err)'],['../classsiddiqsoft_1_1arrp_1_1resource__guard.html#a302c48464f6266f8a712b452816d79bd',1,'siddiqsoft::arrp::resource_guard::resource_guard(resource_guard &amp;&amp;src) noexcept(std::is_nothrow_move_constructible_v&lt; T &gt; &amp;&amp;std::is_nothrow_move_constructible_v&lt; PutbackCallbackFunc &gt;)'],['../api_reference.html#resource_guard_api',1,'resource_guard&amp;lt;T&amp;gt;']]],
  ['resource_5fpool_5',['resource_pool',['../classsiddiqsoft_1_1arrp_1_1resource__pool.html',1,'siddiqsoft::arrp::resource_pool&lt; T &gt;'],['../classsiddiqsoft_1_1arrp_1_1resource__pool.html#a0909de3000c0be9da4fd96f120f8b9e7',1,'siddiqsoft::arrp::resource_pool::resource_pool(resource_pool &amp;)=delete'],['../classsiddiqsoft_1_1arrp_1_1resource__pool.html#a3e13115fd9102b69c57df805675f8572',1,'siddiqsoft::arrp::resource_pool::resource_pool(resource_pool &amp;&amp;src)=delete'],['../classsiddiqsoft_1_1arrp_1_1resource__pool.html#a1ad6399df589bfd554f3e32078e06512',1,'siddiqsoft::arrp::resource_pool::resource_pool(uint8_t init_capacity=resource_pool_limits::DefaultCapacity, std::function&lt; void(T &amp;)&gt; &amp;&amp;on_shutdown_callback={})'],['../classsiddiqsoft_1_1arrp_1_1resource__pool.html#aec9b588016ce92d69bd21688c74b5bdb',1,'siddiqsoft::arrp::resource_pool::resource_pool(std::function&lt; void(T &amp;)&gt; &amp;&amp;on_shutdown_callback)'],['../api_reference.html#resource_pool_api',1,'resource_pool&amp;lt;T&amp;gt;']]],
  ['resources_6',['resources',['../usage_guide.html#usage_basics',1,'Borrowing seeded resources'],['../usage_guide.html#usage_cleanup',1,'Cleaning up available resources']]],
  ['return_5fto_5fpool_7',['return_to_pool',['../classsiddiqsoft_1_1arrp_1_1resource__pool.html#aab51a25b9c6305e20a9f7abcb5b6343c',1,'siddiqsoft::arrp::resource_pool']]],
  ['rules_8',['Lifetime rules',['../index.html#lifecycle',1,'']]]
];
