var searchData=
[
  ['safety_0',['Safety',['../security.html#autotoc_md94',1,'Exception Safety'],['../security.html#autotoc_md92',1,'Memory Safety'],['../security.html#shutdown_safety',1,'Shutdown Safety'],['../api.html#autotoc_md26',1,'Thread Safety'],['../api.html#autotoc_md55',1,'Thread Safety'],['../security.html#autotoc_md93',1,'Thread Safety'],['../security.html#thread_safety',1,'Thread Safety'],['../security.html#autotoc_md95',1,'Type Safety']]],
  ['scoped_20resource_20usage_1',['Scoped Resource Usage',['../examples.html#ex_scoped_usage',1,'']]],
  ['scoped_20resource_20wrapper_2',['Scoped Resource Wrapper',['../usage_guide.html#rp_scoped_resource',1,'']]],
  ['scoped_20resource_20wrapper_20type_3',['SRT - Scoped Resource Wrapper Type',['../api.html#autotoc_md7',1,'']]],
  ['scoped_5fresource_4',['scoped_resource',['../api.html#autotoc_md28',1,'scoped_resource'],['../api.html#autotoc_md59',1,'scoped_resource'],['../quick_reference.html#autotoc_md79',1,'scoped_resource&amp;lt;T&amp;gt;']]],
  ['security_5',['Callback Security',['../security.html#callback_security',1,'']]],
  ['security_20checklist_6',['Security Checklist',['../security.html#security_checklist',1,'']]],
  ['security_20features_7',['Built-in Security Features',['../security.html#security_features',1,'']]],
  ['security_20guide_8',['Security Guide',['../security.html',1,'']]],
  ['see_20also_9',['See Also',['../index.html#see_also',1,'']]],
  ['serialization_10',['Serialization',['../security.html#autotoc_md114',1,'JSON Serialization'],['../usage_guide.html#adv_json_serialization',1,'JSON Serialization']]],
  ['setup_11',['Compiler Setup',['../getting_started.html#compiler_setup',1,'']]],
  ['shutdown_12',['Graceful Shutdown',['../security.html#autotoc_md112',1,'']]],
  ['shutdown_20safety_13',['Shutdown Safety',['../security.html#shutdown_safety',1,'']]],
  ['size_14',['size',['../api.html#autotoc_md18',1,'size'],['../quick_reference.html#autotoc_md82',1,'size()'],['../usage_guide.html#autotoc_md118',1,'size()']]],
  ['srt_20scoped_20resource_20wrapper_20type_15',['SRT - Scoped Resource Wrapper Type',['../api.html#autotoc_md7',1,'']]],
  ['start_16',['Quick Start',['../index.html#quickstart',1,'']]],
  ['started_17',['Getting Started',['../getting_started.html',1,'']]],
  ['state_18',['Monitoring Pool State',['../api.html#autotoc_md53',1,'']]],
  ['static_20members_19',['Static Members',['../api.html#autotoc_md23',1,'']]],
  ['steps_20',['Next Steps',['../getting_started.html#next_steps',1,'']]],
  ['strategy_21',['Understanding the Mutex Strategy',['../security.html#autotoc_md102',1,'']]],
  ['studio_202019_20or_20later_22',['Visual Studio 2019 or later',['../getting_started.html#autotoc_md66',1,'']]],
  ['support_23',['Compiler Support',['../api.html#autotoc_md61',1,'']]]
];
