var searchData=
[
  ['c_0',['ARRP - Auto Returning Resource Pool for Modern C++',['../index.html',1,'']]],
  ['callback_1',['Callback',['../api.html#autotoc_md2',1,'Constructor with Cleanup Callback'],['../api.html#autotoc_md1',1,'Constructor with Factory Callback'],['../usage_guide.html#ug_custom_factory',1,'Custom Factory Callback']]],
  ['capacity_20and_20auto_20add_20policy_2',['Constructor with Capacity and Auto-Add Policy',['../api.html#autotoc_md0',1,'']]],
  ['capacity_20management_3',['Capacity Management',['../index.html#autotoc_md24',1,'']]],
  ['characteristics_4',['Characteristics',['../api.html#api_memory',1,'Memory Characteristics'],['../api.html#api_performance',1,'Performance Characteristics']]],
  ['checking_20resource_20validity_5',['Checking Resource Validity',['../usage_guide.html#ug_check_validity',1,'']]],
  ['class_6',['Class',['../api.html#api_resource_pool',1,'resource_pool Class'],['../api.html#api_scoped_resource',1,'scoped_resource Class']]],
  ['cleanup_20callback_7',['Constructor with Cleanup Callback',['../api.html#autotoc_md2',1,'']]],
  ['clear_8',['clear()',['../api.html#autotoc_md6',1,'']]],
  ['cmake_20recommended_9',['Using CMake (Recommended)',['../index.html#autotoc_md20',1,'']]],
  ['concepts_10',['Key Concepts',['../index.html#key_concepts',1,'']]],
  ['constraints_11',['Constraints',['../api.html#api_constraints',1,'']]],
  ['constructor_12',['Constructor',['../api.html#autotoc_md8',1,'Explicit Constructor'],['../api.html#autotoc_md9',1,'In-Place Constructor'],['../api.html#autotoc_md15',1,'Move Constructor']]],
  ['constructor_20with_20capacity_20and_20auto_20add_20policy_13',['Constructor with Capacity and Auto-Add Policy',['../api.html#autotoc_md0',1,'']]],
  ['constructor_20with_20cleanup_20callback_14',['Constructor with Cleanup Callback',['../api.html#autotoc_md2',1,'']]],
  ['constructor_20with_20factory_20callback_15',['Constructor with Factory Callback',['../api.html#autotoc_md1',1,'']]],
  ['constructors_16',['Constructors',['../api.html#api_rp_constructors',1,'Constructors'],['../api.html#api_sr_constructors',1,'Constructors']]],
  ['consumed_20resources_17',['Invalidating Consumed Resources',['../usage_guide.html#ug_invalidate_consumed',1,'']]],
  ['copyright_18',['Copyright',['../index.html#copyright',1,'']]],
  ['creating_20a_20pool_19',['Creating a Pool',['../usage_guide.html#ug_create_pool',1,'']]],
  ['custom_20factory_20callback_20',['Custom Factory Callback',['../usage_guide.html#ug_custom_factory',1,'']]],
  ['custom_20types_21',['Using Custom Types',['../usage_guide.html#ug_custom_types',1,'']]]
];
