var searchData=
[
  ['c_0',['ARRP - Auto Returning Resource Pool for Modern C++',['../index.html',1,'']]],
  ['call_20pool_20methods_1',['Critical Rule: Factory Callbacks Must Not Call Pool Methods',['../security.html#autotoc_md103',1,'']]],
  ['callback_20practices_2',['Callback Practices',['../security.html#autotoc_md97',1,'✅ Good Callback Practices'],['../security.html#autotoc_md98',1,'❌ Bad Callback Practices']]],
  ['callback_20security_3',['Callback Security',['../security.html#callback_security',1,'']]],
  ['callbackdonotautoaddresource_4',['CallbackDoNotAutoAddResource',['../api.html#autotoc_md24',1,'']]],
  ['callbacks_20must_20not_20call_20pool_20methods_5',['Critical Rule: Factory Callbacks Must Not Call Pool Methods',['../security.html#autotoc_md103',1,'']]],
  ['capacity_6',['InitCapacity - Initial Pool Capacity',['../api.html#autotoc_md8',1,'']]],
  ['capacity_20constraint_7',['1. Capacity Constraint',['../api.html#autotoc_md10',1,'']]],
  ['capacity_20limits_8',['Capacity Limits',['../security.html#autotoc_md106',1,'']]],
  ['capacity_20management_9',['Capacity Management',['../usage_guide.html#rp_capacity',1,'']]],
  ['capacity_20planning_10',['Capacity Planning',['../usage_guide.html#bp_capacity',1,'']]],
  ['checkin_11',['checkin',['../api.html#autotoc_md20',1,'checkin'],['../usage_guide.html#autotoc_md117',1,'checkin()']]],
  ['checkin_20t_12',['checkin(T&amp;amp;&amp;amp;)',['../quick_reference.html#autotoc_md81',1,'']]],
  ['checklist_13',['Security Checklist',['../security.html#security_checklist',1,'']]],
  ['checkout_14',['checkout',['../api.html#autotoc_md19',1,'checkout'],['../quick_reference.html#autotoc_md80',1,'checkout()'],['../usage_guide.html#autotoc_md116',1,'checkout()']]],
  ['circular_20dependencies_15',['Circular Dependencies',['../security.html#autotoc_md99',1,'']]],
  ['clang_2010_16',['Clang 10+',['../getting_started.html#autotoc_md68',1,'']]],
  ['clause_17',['Template Constraints (Requires Clause)',['../api.html#autotoc_md9',1,'']]],
  ['cleanup_18',['Resource Cleanup',['../security.html#autotoc_md113',1,'']]],
  ['clear_19',['clear',['../api.html#autotoc_md21',1,'clear'],['../quick_reference.html#autotoc_md83',1,'clear()'],['../usage_guide.html#autotoc_md119',1,'clear()']]],
  ['client_20connection_20pool_20',['HTTP Client Connection Pool',['../examples.html#ex_http_client',1,'']]],
  ['cmake_20recommended_21',['CMake Recommended',['../getting_started.html#autotoc_md64',1,'Using CMake (Recommended)'],['../index.html#autotoc_md75',1,'Using CMake (Recommended)']]],
  ['common_20issues_22',['Common Issues',['../quick_reference.html#qr_troubleshooting',1,'']]],
  ['common_20methods_23',['Common Methods',['../quick_reference.html#qr_methods',1,'']]],
  ['common_20patterns_24',['Common Patterns',['../api.html#autotoc_md48',1,'Common Patterns'],['../getting_started.html#common_patterns',1,'Common Patterns']]],
  ['compilation_25',['Compilation',['../quick_reference.html#qr_compilation',1,'']]],
  ['compilation_20errors_26',['Compilation Errors',['../getting_started.html#autotoc_md73',1,'']]],
  ['compiler_20setup_27',['Compiler Setup',['../getting_started.html#compiler_setup',1,'']]],
  ['compiler_20support_28',['Compiler Support',['../api.html#autotoc_md61',1,'']]],
  ['components_29',['Main Components',['../index.html#components',1,'']]],
  ['components_20at_20a_20glance_30',['Components at a Glance',['../quick_reference.html#qr_components',1,'']]],
  ['concept_31',['NonNumericMoveConstructible Concept',['../quick_reference.html#autotoc_md86',1,'']]],
  ['concepts_32',['Concepts',['../api.html#autotoc_md45',1,'']]],
  ['configuration_33',['Mutex Configuration',['../api.html#autotoc_md63',1,'']]],
  ['connection_20pool_34',['Connection Pool',['../examples.html#ex_database_connections',1,'Database Connection Pool'],['../examples.html#ex_http_client',1,'HTTP Client Connection Pool']]],
  ['considerations_35',['Considerations',['../api.html#autotoc_md57',1,'Performance Considerations'],['../usage_guide.html#performance',1,'Performance Considerations']]],
  ['consistency_36',['Lock Ordering and Consistency',['../security.html#autotoc_md104',1,'']]],
  ['constraint_37',['Constraint',['../api.html#autotoc_md10',1,'1. Capacity Constraint'],['../api.html#autotoc_md11',1,'2. Resource Type Constraint'],['../api.html#autotoc_md12',1,'3. Wrapper Type Constraint']]],
  ['constraints_38',['Type Constraints',['../quick_reference.html#qr_constraints',1,'']]],
  ['constraints_20and_20limitations_39',['Constraints and Limitations',['../api.html#autotoc_md25',1,'']]],
  ['constraints_20requires_20clause_40',['Template Constraints (Requires Clause)',['../api.html#autotoc_md9',1,'']]],
  ['constructor_41',['Constructor',['../api.html#autotoc_md35',1,'Explicit Constructor'],['../api.html#autotoc_md36',1,'Move Constructor']]],
  ['constructor_20with_20auto_20add_20policy_42',['Constructor with Auto-Add Policy',['../api.html#autotoc_md16',1,'']]],
  ['constructor_20with_20custom_20factory_43',['Constructor with Custom Factory',['../api.html#autotoc_md15',1,'']]],
  ['constructors_44',['Constructors',['../api.html#autotoc_md14',1,'Constructors'],['../api.html#autotoc_md34',1,'Constructors']]],
  ['contents_45',['Table of Contents',['../api.html#autotoc_md0',1,'']]],
  ['conversion_20operator_46',['Type Conversion Operator',['../api.html#autotoc_md40',1,'']]],
  ['copyright_47',['Copyright',['../index.html#copyright',1,'']]],
  ['critical_20exceptions_48',['Critical Exceptions',['../security.html#autotoc_md109',1,'']]],
  ['critical_20rule_3a_20factory_20callbacks_20must_20not_20call_20pool_20methods_49',['Critical Rule: Factory Callbacks Must Not Call Pool Methods',['../security.html#autotoc_md103',1,'']]],
  ['custom_20factory_50',['Custom Factory',['../api.html#autotoc_md15',1,'Constructor with Custom Factory'],['../quick_reference.html#qr_pattern_factory',1,'Custom Factory'],['../quick_reference.html#autotoc_md88',1,'Example 2: Custom Factory'],['../api.html#autotoc_md50',1,'Resource Pool with Custom Factory']]],
  ['custom_20factory_20example_51',['Custom Factory Example',['../index.html#resource_pool_custom',1,'']]],
  ['custom_20resource_20factory_52',['Custom Resource Factory',['../examples.html#ex_custom_factory',1,'Custom Resource Factory'],['../usage_guide.html#rp_factory',1,'Custom Resource Factory'],['../getting_started.html#autotoc_md70',1,'Pattern 2: Custom Resource Factory']]],
  ['custom_20resource_20types_53',['Custom Resource Types',['../usage_guide.html#adv_custom_types',1,'']]]
];
